### ISSUE TITLE
Vaporware?

### ISSUE THREAD

**Issue by 9mjb** [koknat/callGraph#7] opened 2022-05-12 13:45 UTC
No code?  Is this a test set?

**Comment by koknat** [comment] 2022-05-12 15:47
It's the code.
The executable is 'callGraph'

**Comment by 9mjb** [comment] 2022-05-12 18:57
Wow.  I've been seeing .py too long... and can't recognize a program anymore.  Plus GitHub isn't doing directory listings that have some information showing what is executable. Sorry.  Thanks for responding.  I'll check it out.

**Comment by koknat** [comment] 2022-05-21 20:40
closing issue as 'not a bug'

**Closed** 2022-05-21 20:39 UTC
